# Generated by Django 2.0.4 on 2018-04-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='author',
        ),
    ]
